version: '3.8'
services:
  ############################
  # Node app + Dapr sidecar
  ############################
  controller:
    build: ../node
    ports:
      - "3000"
      - "50001"
    depends_on:
      - redis
      - placement
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.12factor.rule=Host(`12factor.127.0.0.1.nip.io`)"
    networks:
      - dapr-callendar-network
    environment:
      - EVENT_APP=go-events
  controller-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "controller",
     "-app-port", "3000",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/components"]
    volumes:
      - "../components/:/components"
    depends_on:
      - controller
    network_mode: "service:controller"
  ############################
  # Python app + Dapr sidecar
  ############################
  messages:
    build: ../python
    depends_on:
      - redis
      - placement
    networks:
      - dapr-callendar-network
    environment:
      - FLASK_RUN_PORT=5000
  messages-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "messages",
     "-app-port", "5000",    
     "-dapr-http-port", "3501",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "../components/:/components"
    depends_on:
      - messages
    network_mode: "service:messages"
  ############################
  # Go app + Dapr sidecar
  ############################
  go-events:
    build: ../go
    environment:
      - DAPR_HTTP_PORT=3503
    depends_on:
      - redis
      - placement
    networks:
      - dapr-callendar-network
  go-events-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "go-events",
     "-app-port", "6000",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3503",
     "-components-path", "/components"]
    volumes:
      - "../components/:/components"
    depends_on:
      - go-events
    network_mode: "service:go-events"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-callendar-network
  ############################
  # Redis state store
  ############################
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=Pa55w.rd
    ports:
      - '6379'
    networks:
      - dapr-callendar-network
    volumes:
      - 'redis_data:/bitnami/redis/data'
  ############################
  # traefik api gateway
  ############################
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dapr-callendar-network
      - default

volumes:
  redis_data:
    driver: local
networks:
    dapr-callendar-network:
