prometheus:
  prometheusSpec:
    scrapeInterval: 5s
    scrapeTimeout: 3s
    evaluationInterval: 30s
    enableFeatures:
     - exemplar-storage
    additionalScrapeConfigs:
      - job_name: 'dapr'
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              own_namespace: true
              names: [opentelemetry]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_dapr_collector_demo]
            action: keep
            regex: true
      - job_name: 'traefik'
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              own_namespace: true
              names: [kube-system]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: "traefik"
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - opencost.opencost
          type: 'A'
          port: 9003
      # - job_name: kubecost
      #   honor_labels: true
      #   scrape_interval: 1m
      #   scrape_timeout: 10s
      #   metrics_path: /metrics
      #   scheme: http
      #   dns_sd_configs:
      #   - names:
      #     - kubecost-cost-analyzer.<namespace-of-your-kubecost>
      #     type: 'A'
      #     port: 9003