apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubecost-ingress
  namespace: kubecost
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kubecost.127.0.0.1.nip.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: kubecost-cost-analyzer
          port: 9090