apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: locust-ingress
  namespace: 12-factor-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`locust.127.0.0.1.nip.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: locust
          port: 8089