apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: events
  namespace: 12-factor-app
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    # value: "jW6UBn6aea" # kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: 12-factor-app
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    # value: "jW6UBn6aea" # kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes
