apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: opencost-ingress
  namespace: opencost
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`openUI.127.0.0.1.nip.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        name: opencost
        port:
          name: opencost-ui
