apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: events
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: "Pa55w.rd"
  - name: actorStateStore
    value: "true"